language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7 DB=sqlite
  - DJANGO=1.3.1 DB=sqlite
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -r requirements.txt
  - pip install -q -e . --use-mirrors
script:
  -  python setup.py test
